#!/usr/bin/env python3
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
landing = (ROOT / 'frontend/src/pages/Landing/Landing.tsx').read_text()
app = (ROOT / 'frontend/src/pages/App/AppPage.tsx').read_text()
app_css = (ROOT / 'frontend/src/pages/App/AppPage.module.css').read_text()
sidebar_css = (ROOT / 'frontend/src/components/Sidebar/Sidebar.module.css').read_text()
sidebar = (ROOT / 'frontend/src/components/Sidebar/Sidebar.tsx').read_text()
step_player = (ROOT / 'frontend/src/components/StepPlayer/StepPlayer.tsx').read_text()
concept_css = (ROOT / 'frontend/src/components/Visualization/ConceptViz.module.css').read_text()
docs = (ROOT / 'frontend/src/pages/Docs/DocsPage.tsx').read_text()
index_css = (ROOT / 'frontend/src/index.css').read_text()
bar_viz = (ROOT / 'frontend/src/components/Visualization/BarViz.tsx').read_text()
graph_viz = (ROOT / 'frontend/src/components/Visualization/GraphViz.tsx').read_text()
trace_viz = (ROOT / 'frontend/src/components/Visualization/TraceViz.tsx').read_text()
seed = (ROOT / 'catalog/seeds/algorithms.sql').read_text()

failures: list[str] = []

def require(condition: bool, message: str) -> None:
    if not condition:
        failures.append(message)

# Canonical bundled catalog facts.
template_count = 0
categories: set[str] = set()
difficulties: dict[str, int] = {}
for match in re.finditer(
    r"INSERT INTO templates \(name, category, difficulty, time_complexity, space_complexity(?:, render_type)?\) VALUES\n(.*?);",
    seed,
    re.S,
):
    for row in re.finditer(
        r"\('(?:''|[^'])*',\s*'((?:''|[^'])*)',\s*'((?:''|[^'])*)',\s*'(?:''|[^'])*',\s*'(?:''|[^'])*'(?:,\s*'(?:''|[^'])*')?\)",
        match.group(1),
    ):
        template_count += 1
        categories.add(row.group(1))
        difficulties[row.group(2)] = difficulties.get(row.group(2), 0) + 1

require(template_count == 55, f'expected 55 seeded templates, found {template_count}')
require(len(categories) == 11, f'expected 11 categories, found {len(categories)}')
require(difficulties == {'Fundamental': 15, 'Intermediate': 26, 'Advanced': 14}, f'unexpected difficulty counts: {difficulties}')

# Landing simplicity + real preview.
require('buildBubblePreview' in landing and 'for (let pass = 0;' in landing, 'landing preview must be generated by Bubble Sort logic')
require('fetchTemplates' not in landing and 'heroStats' not in landing, 'landing should not behave like a catalog/metrics dashboard')
require('catalogSection' not in landing and 'LEARNING_STEPS' not in landing and 'finalCta' not in landing, 'landing still contains the removed long-form marketing sections')
require("navigate('/app?mode=guided')" in landing and "navigate('/app?mode=custom')" in landing, 'landing CTAs must deep-link to the intended learning mode')
require('Story mode' in landing and 'Step explanations' in landing and 'Source on demand' in landing, 'landing should communicate the three core learning capabilities')

# Viewport shell: navigation stays put while lesson content owns scrolling.
require('height: 100dvh;' in app_css and '.shell {' in app_css and 'overflow: hidden;' in app_css, 'app shell must be locked to the viewport')
require('.main {' in app_css and 'height: 100%;' in app_css and 'overflow: hidden;' in app_css, 'main frame must not grow the document')
require('overflow-y: auto;' in app_css and 'overscroll-behavior: contain;' in app_css, 'workspace must own vertical overflow at stacked breakpoints')
require('height: 100%;' in sidebar_css and 'overflow-y: auto;' in sidebar_css, 'desktop sidebar must stay viewport-bound with independent overflow')

# App mode + drawer behavior.
require("searchParams.get('mode') === 'guided'" in app, 'app does not honor guided-mode deep link')
require("document.body.style.overflow = 'hidden'" in sidebar, 'mobile drawer must lock background scrolling')
require('LANGUAGES[item as Language]?.label' in sidebar, 'mobile/desktop language hint should use user-facing language labels')

# Player + responsive concept robustness.
require("currentStep >= totalSteps - 1) onStepChange(0)" in step_player, 'Step Player does not restart when replaying the final frame')
require('disabled={totalSteps <= 1}' in step_player, 'single-step traces should disable Play/Pause')
require('aria-label="playback speed"' in step_player, 'speed control is missing an accessible label')
require('.stringSearch { overflow-x: auto' in concept_css, 'string visualization should scroll locally on narrow screens')
require('@media (max-width: 480px)' in concept_css and '.sieve { grid-template-columns: repeat(5' in concept_css, 'small-screen concept overrides are missing')

# Docs + global UI safeguards.
require('LANGUAGE_LIST.map' in docs, 'docs language matrix should use shared runtime metadata')
require('55 canonical' in docs and '~50' not in docs, 'docs catalog count is stale')
require('step player at the bottom' not in docs and 'dropdown' not in docs, 'docs still describe the old UI flow')
require('prefers-reduced-motion: reduce' in index_css, 'reduced-motion support is missing')
require('body { overflow-x: hidden; }' in index_css, 'whole-page horizontal overflow safeguard is missing')
require("return 'complete'" in bar_viz and '.map((value, index) =>' in bar_viz, 'array renderer completion/index safeguards are missing')
require('weight !== undefined ? (' in graph_viz, 'unweighted graph edges still render empty weight badges')
require('allSteps.length === 0 ? 0' in trace_viz, 'empty trace should report 0% progress')

if failures:
    print('UI regression verification FAILED')
    for failure in failures:
        print(f'  - {failure}')
    sys.exit(1)

print(f'PASS bundled catalog facts: {template_count} lessons, {len(categories)} categories, {difficulties}')
print('PASS landing is intentionally simple and the Bubble Sort preview is algorithm-generated')
print('PASS guided/custom landing CTAs open the intended app mode')
print('PASS app shell/sidebar stay viewport-bound while workspace content scrolls independently')
print('PASS mobile drawer scroll lock + user-facing language labels')
print('PASS Step Player final-frame replay + single-step/accessibility guards')
print('PASS narrow concept visualizations wrap/scroll locally')
print('PASS Docs use current runtime metadata and current UI workflow')
print('PASS reduced-motion and whole-page overflow safeguards')
print('PASS array/graph/trace renderer edge-case fixes')
